updated recommend function to blacklist classes with same title as input and input classes
p-ai-org/p-recommender pull request #39
Opened 2022-12-02 23:32 UTC by TiloRC

2022-12-02 23:36 UTC, saatvikkher commented
Add screenshots of the site being tested locally.

2022-12-02 23:37 UTC, saatvikkher requested changes
Do not commit metadata. Make sure you only commit necessary files. There's 10 changed files in the commit and many are unnecessary/metadata.

2022-12-02 23:38 UTC, saatvikkher commented on app.py
> +    #print(recommend2([coursename]))
No commented-out print statements in main.

2022-12-02 23:39 UTC, saatvikkher commented on recommend_GloVe/.#recommend_GloVe.py
> +reneau-cardoso@times-mbp.local.87556
This file shouldn't be here.

2022-12-02 23:58 UTC, TiloRC commented
Removed meta data files and checked to see if the flask app still ran after changes

2022-12-03 00:15 UTC, TiloRC commented
Noticed some other bugs. Will work on this later.

2022-12-03 00:15 UTC, closed without merging